config/routes.rb
Beery::Application.routes.draw do

  root 'beers#index'

  resources :beers

end

app/models/beer.rb
# == Schema Information
#
# Table name: beers
#
#  id         :integer          not null, primary key
#  brewer_id  :integer
#  style_id   :integer
#  country_id :integer
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Beer < ActiveRecord::Base
  belongs_to :brewer
  belongs_to :style
  belongs_to :country
  has_many :users, :through => :beers_user
  has_many :beers_user

  validates :name, presence: true

  def as_json(options = {})
    json = super(options)
    json[:brewer] = brewer if brewer.present?
    json[:style] = style if style.present?
    json[:country] = country if country.present?
    json
  end
end

app/models/beers_user.rb
# == Schema Information
#
# Table name: beers_users
#
#  id         :integer          not null, primary key
#  created_at :datetime
#  updated_at :datetime
#

class BeersUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :beer
end

app/models/brewer.rb
# == Schema Information
#
# Table name: brewers
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  country_id :integer
#  created_at :datetime
#  updated_at :datetime
#

class Brewer < ActiveRecord::Base
  has_many :beers
  has_many :styles
  belongs_to :country
end

app/models/brewers_location.rb
# == Schema Information
#
# Table name: brewers_locations
#
#  id          :integer          not null, primary key
#  brewer_id   :integer
#  location_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class BrewersLocation < ActiveRecord::Base
  belongs_to :brewer
  belongs_to :location
end

app/models/country.rb
# == Schema Information
#
# Table name: countries
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  iso_code   :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Country < ActiveRecord::Base
  has_many :brewers
end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  latitude   :string(255)
#  longitude  :string(255)
#  city       :string(255)
#  state      :string(255)
#  metadata   :string(255)
#  country_id :integer
#  created_at :datetime
#  updated_at :datetime
#

class Location < ActiveRecord::Base
  has_many :users
  has_many :brewers, :through => :brewers_location
  belongs_to :country
end

app/models/style.rb
# == Schema Information
#
# Table name: styles
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Style < ActiveRecord::Base
  has_many :beers
  has_many :brewers
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  email       :string(255)
#  age         :string(255)
#  gender      :string(255)
#  location_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class User < ActiveRecord::Base
  has_many :beers, :through => :beers_user
  has_many :beers_user
  belongs_to :location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]

  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.all
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
    @beer = Beer.find(params[:id])
  end

  # GET /beers/new
  def new
    @beer = Beer.new
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(beer_params)
    puts @beer.inspect

    respond_to do |format|
      if @beer.save
        format.html { redirect_to @beer, notice: 'Beer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @beer }
      else
        format.html { render action: 'new' }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:name)
    end
end

app/controllers/brewers_controller.rb
class BrewersController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.haml
= form_for @beer do |f|
  - if @beer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@beer.errors.count, "error")} prohibited this beer from being saved:"
      %ul
        - @beer.errors.full_messages.each do |msg|
          %li= msg

  = f.label :name
  = f.text_field :name

  .actions
    = f.submit 'Save'

app/views/beers/edit.html.haml
%h1 Editing beer

= render 'form'

= link_to 'Show', @beer
\|
= link_to 'Back', beers_path

app/views/beers/index.html.haml
%h1 Listing beers

%table
  %tr
    %th
    %th
    %th
    %th

  - @beers.each do |beer|
    %tr
      %td= beer.name
      %td= link_to 'Show', beer
      %td= link_to 'Edit', edit_beer_path(beer)
      %td= link_to 'Destroy', beer, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Beer', new_beer_path

app/views/beers/new.html.haml
%h1 New beer

= render 'form'

= link_to 'Back', beers_path

app/views/beers/show.html.haml
%p#notice= notice

%p
  %strong Name:
  = @beer.name

= link_to 'Edit', edit_beer_path(@beer)
\|
= link_to 'Back', beers_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="beery">
  <head>
    <title>Beery</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application"%>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div ng-view>
      <%= yield %>
    </div>
  </body>
</html>